### ISSUE TITLE
Sub-sub domain fix

### ISSUE THREAD

**Issue by larryboymi** [ocelotconsulting/node-letsencrypt-lambda#13]
From @phoenix-zhu 's [request](https://github.com/ocelotconsulting/node-letsencrypt-lambda/issues/10#issuecomment-282940194) in #10.... 

> to get a cert for a non-secondary level domain like 'a.b.c.com' because the code here(https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/aws/route53/getHostedZoneId.js#L8) only cuts the last 2 parts of the domain for zone name.

**Comment by larryboymi** [comment]
@phoenix-zhu ... I just pushed a632f88e, which I think should solve your issue. It requires a little more configuration, as I have no idea the limits at which a user might utilize domain levels with hosted zones (theoretically up to 127, but not sure who would do that). Please see the documentation on the differences in the config JSON, and let me know what you think. If this works for you, I'll close the issue. Thanks!

**Comment by phoenix-zhu** [comment]
Thanks, @larryboymi it works fine.
I really appreciate all the update you've done for me. You are awesome.

**Comment by larryboymi** [comment]
No problem @phoenix-zhu ... thanks for your help in finding these outlying issues. Glad I could help.
