### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by radekg** [ocelotconsulting/node-letsencrypt-lambda#20]
Hi, maybe it's an obvious question but better to be safe than sorry. What's the license?

**Comment by radekg** [comment]
Uh, found it: https://github.com/ocelotconsulting/node-letsencrypt-lambda/issues/11

**Comment by larryboymi** [comment]
It's ISC, however I'd definitely love to hear/see what you're doing with the project if you could share, especially if it will make it better.

Thanks!
