### ISSUE TITLE
Unable to request new cert and replace it into S3 when the cert is going to expire.

### ISSUE THREAD

**Issue by wooiliang** [ocelotconsulting/node-letsencrypt-lambda#8]
https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/acme/certify/getCertificate.js#L14

Hi, I have a question regarding this line of code. Seems I only able to create a new cert if the ${domain}.json not exist in the S3. So, how can I able to request a new cert if the old cert is gonna expire?

Thanks!

**Comment by larryboymi** [comment]
Hi @wooiliang ... actually if you look at [this line](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/util/isExpired.js#L18), there is code prior to the flow that will check to see if a certificate is expired or within 30 days of expiration, and if so it will re-generate.

In fact, that is the main use case for this project. On a periodic basis (likely daily), the check is performed to see if a certificate is expired (or close), and then renew the certificate. There are other projects in our org that can be used to renew the cert in an [ELB](https://github.com/ocelotconsulting/elb-ssl-cert-lambda) or in [IAM](https://github.com/ocelotconsulting/iam-server-cert-lambda).

Let me know if you still have issues.

**Comment by wooiliang** [comment]
Hi @larryboymi , yes the isExpired.js does the checking [if the "Date" today is lesser than "notBefore" or greater than "notAfter" or lesser than 30 days of expiration, then it will return true.](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/util/isExpired.js#L9) 

After returning true, the script will [regenerate](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/app.js#L9) the cert. ( Of cause if false, then going back to bed :) )

However, when come to this [point](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/acme/certify/getCertificate.js#L5), I cannot create a new cert because the [${domain}.json](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/acme/certify/getCertificate.js#L9) is already exist inside the S3 bucket.

What I expect is when regenerating the new cert, the new cert (${domain}.json) will actually replace the old cert (${domain}.json) in S3. 

Please let me know if it is expected or I misunderstand the codes somewhere. Thanks.

**Comment by larryboymi** [comment]
Thanks for spotting that @wooiliang ... check 5b9428d for the fix... specifically [this](https://github.com/ocelotconsulting/node-letsencrypt-lambda/blob/master/src/acme/generateCertificate.js#L12). Let me know if that addresses your issue, and I'll close this.

**Comment by wooiliang** [comment]
Hi @larryboymi , thanks for the fix, it did solve the issue. You may proceed to close the issue. Thanks again! :smile:

**Comment by larryboymi** [comment]
No problem! Hope this project helps you..
